//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eat_BeatApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class multimedia
    {
        public int idUser { get; set; }
        public int idMultimedia { get; set; }
        public int idMultimediaType { get; set; }
        public string url { get; set; }
        public Nullable<decimal> size { get; set; }
    
        public virtual multimedia_type multimedia_type { get; set; }
        public virtual user user { get; set; }
    }
}
